import imagenes from "./imagenes";

export const productos = [
  {
    id: 1,
    img: imagenes.img13,
    nombre: "Docena de autor",
    precio: 17000,
    stock: 10,
    cantidad: 1,
    category: "medialuna",
  },
  {
    id: 2,
    img: imagenes.img14,
    nombre: "1/2 Docena de autor",
    precio: 10000,
    stock: 10,
    cantidad: 1,
    category: "medialuna",
  },
  {
    id: 3,
    img: imagenes.img15,
    nombre: "Docena común",
    precio: 11000,
    stock: 10,
    cantidad: 1,
    category: "medialuna",
  },
  {
    id: 4,
    img: imagenes.img4,
    nombre: "1/2 Docena común",
    precio: 6500,
    stock: 10,
    cantidad: 1,
    category: "medialuna",
  },
  {
    id: 5,
    img: imagenes.img13,
    nombre: "Docena clasica",
    precio: 15000,
    stock: 10,
    cantidad: 1,
    category: "medialuna",
  },
  {
    id: 6,
    img: imagenes.img14,
    nombre: "1/2 Docena clasica",
    precio: 8500,
    stock: 10,
    cantidad: 1,
    category: "medialuna",
  },
  {
    id: 7,
    img: imagenes.img21,
    nombre: "Porción de Carrot Cake",
    precio: 7000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 8,
    img: imagenes.img29,
    nombre: "Porcion de Key Lemon",
    precio: 7000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 9,
    img: imagenes.img22,
    nombre: "Porción de Frutos Rojos",
    precio: 7000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 10,
    img: imagenes.img24,
    nombre: "Porción de Red Velvet",
    precio: 7000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 11,
    img: imagenes.img28,
    nombre: "Porción de Doble Oreo",
    precio: 9000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 12,
    img: imagenes.img26,
    nombre: "Porción de Matilda",
    precio: 9000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 13,
    img: imagenes.img27,
    nombre: "Porción de Doble Mousse de chocolate",
    precio: 9000,
    stock: 10,
    cantidad: 1,
    category: "Porción",
  },
  {
    id: 14,
    img: imagenes.img18,
    nombre: "Alfajor de Maicena",
    precio: 2800,
    stock: 10,
    cantidad: 1,
    category: "otro",
  },
  {
    id: 15,
    img: imagenes.img17,
    nombre: "Alfajor Blanco",
    precio: 3500,
    stock: 10,
    cantidad: 1,
    category: "otro",
  },
  {
    id: 16,
    img: imagenes.img16,
    nombre: "Alfajor Negro",
    precio: 3500,
    stock: 10,
    cantidad: 1,
    category: "otro",
  },
  {
    id: 17,
    img: imagenes.img12,
    nombre: "Scone de queso",
    precio: 2600,
    stock: 10,
    cantidad: 1,
    category: "otro",
  },
  {
    id: 18,
    img: imagenes.img19,
    nombre: "Bizcochitos dulces x 100gr",
    precio: 500,
    stock: 10,
    cantidad: 1,
    category: "otro",
  },
  {
    id: 19,
    img: imagenes.img20,
    nombre: "Chipá x 100gr",
    precio: 2800,
    stock: 10,
    cantidad: 1,
    category: "otro",
  },
];
