import imagenes from "./imagenes";

export const productos = [
	{
		id: 1,
		img: imagenes.img13,
		nombre: "Docena de autor",
		precio: 8400,
		stock: 10,
		cantidad: 1,
		category: "Medialuna",
	},
	{
		id: 2,
		img: imagenes.img14,
		nombre: "1/2 Docena de autor",
		precio: 4700,
		stock: 10,
		cantidad: 1,
		category: "Medialuna",
	},
	{
		id: 3,
		img: imagenes.img15,
		nombre: "Docena común",
		precio: 4500,
		stock: 10,
		cantidad: 1,
		category: "Medialuna",
	},
	{
		id: 4,
		img: imagenes.img4,
		nombre: "1/2 Docena común",
		precio: 2700,
		stock: 10,
		cantidad: 1,
		category: "Medialuna",
	},
	{
		id: 5,
		img: imagenes.img13,
		nombre: "Docena clasica",
		precio: 5000,
		stock: 10,
		cantidad: 1,
		category: "Medialuna",
	},
	{
		id: 6,
		img: imagenes.img14,
		nombre: "1/2 Docena clasica",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Medialuna",
	},
	{
		id: 7,
		img: imagenes.img21,
		nombre: "Porcion de Key Lemon",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 8,
		img: imagenes.img22,
		nombre: "Porcion de Cheescake de frutos rojos",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 8,
		img: imagenes.img22,
		nombre: "Porcion de Amanda",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 9,
		img: imagenes.img22,
		nombre: "Porcion de Postre de Frutos Rojos",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 10,
		img: imagenes.img25,
		nombre: "Porcion de Patagonia",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 11,
		img: imagenes.img25,
		nombre: "Porcion de Pirineo",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 12,
		img: imagenes.img24,
		nombre: "Porcion de Red Velvet",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 13,
		img: imagenes.img26,
		nombre: "Porcion de Chocotorta",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 14,
		img: imagenes.img28,
		nombre: "Porcion de Doble Oreo",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 15,
		img: imagenes.img26,
		nombre: "Porcion de Matilda",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 16,
		img: imagenes.img27,
		nombre: "Porcion de Doble Mousse de chocolate",
		precio: 3900,
		stock: 10,
		cantidad: 1,
		category: "Porcion",
	},
	{
		id: 17,
		img: imagenes.img14,
		nombre: "Budin de Manzana con nuez",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 18,
		img: imagenes.img14,
		nombre: "Budin de Limon",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 19,
		img: imagenes.img14,
		nombre: "Budin de Chocolate",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 20,
		img: imagenes.img18,
		nombre: "Alfajor de Maicena",
		precio: 800,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 21,
		img: imagenes.img17,
		nombre: "Alfajor Blanco",
		precio: 1200,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 22,
		img: imagenes.img16,
		nombre: "Alfajor Negro",
		precio: 1200,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 23,
		img: imagenes.img14,
		nombre: "Porcion de Tarta de coco",
		precio: 2100,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 24,
		img: imagenes.img14,
		nombre: "Porcion de Pastafrola",
		precio: 2100,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 25,
		img: imagenes.img12,
		nombre: "Scone de queso",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 26,
		img: imagenes.img10,
		nombre: "Cañoncito de dulce de leche",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 27,
		img: imagenes.img10,
		nombre: "Cañoncito de Pastelera",
		precio: 2900,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 28,
		img: imagenes.img19,
		nombre: "Bizcochitos dulces x 100gr",
		precio: 500,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
	{
		id: 29,
		img: imagenes.img20,
		nombre: "Chipá x 100gr",
		precio: 1500,
		stock: 10,
		cantidad: 1,
		category: "Otro",
	},
];
